# -*- coding: utf-8 -*-
import os

from setuptools import find_packages
from setuptools import setup


base_dir = os.path.dirname(__file__)
setup(
    name='elastalert',
    version='0.1.38',
    description='Runs custom filters on Elasticsearch and alerts on matches',
    author='Quentin Long',
    author_email='qlo@yelp.com',
    setup_requires='setuptools',
    license='Copyright 2014 Yelp',
    classifiers=[
        'Programming Language :: Python :: 2.7',
        'License :: OSI Approved :: Apache Software License',
        'Operating System :: OS Independent',
    ],
    entry_points={
        'console_scripts': ['elastalert-create-index=elastalert.create_index:main',
                            'elastalert-test-rule=elastalert.test_rule:main',
                            'elastalert-rule-from-kibana=elastalert.rule_from_kibana:main',
                            'elastalert=elastalert.elastalert:main']},
    packages=find_packages(),
    package_data={'elastalert': ['schema.yaml']},
    install_requires=[
        'asn1crypto==0.24.0',
        'aws-requests-auth==0.4.2',
        'blist==1.3.6',
        'boto3==1.9.104',
        'botocore==1.12.104',
        'certifi==2018.11.29',
        'cffi==1.12.2',
        'chardet==3.0.4',
        'configparser==3.7.3',
        'croniter==0.3.3',
        'cryptography==2.6',
        'defusedxml==0.5.0',
        'docopt==0.6.2',
        'docutils==0.14',
        'elasticsearch==1.9.0',
        'enum34==1.1.6',
        'envparse==0.2.0',
        'exotel==0.1.5',
        'funcsigs==1.0.2',
        'functools32==3.2.3.post2',
        'future==0.17.1',
        'futures==3.2.0',
        'idna==2.8',
        'ipaddress==1.0.22',
        'jira==1.0.14',
        'jmespath==0.9.4',
        'jsonschema==2.6.0',
        'mock==2.0.0',
        'oauthlib==3.0.1',
        'ordereddict==1.1',
        'pbr==5.1.2',
        'pip==19.0.3',
        'pycparser==2.19',
        'PyJWT==1.7.1',
        'pyOpenSSL==19.0.0',
        'PyStaticConfiguration==0.10.4',
        'python-dateutil==2.6.1',
        'python-magic==0.4.15',
        'pytz==2018.9',
        'PyYAML==3.13',
        'requests==2.21.0',
        'requests-oauthlib==1.2.0',
        'requests-toolbelt==0.9.1',
        's3transfer==0.2.0',
        'setuptools==40.8.0',
        'six==1.12.0',
        'stomp.py==4.1.21',
        'texttable==1.6.1',
        'thehive4py==1.6.0',
        'twilio==6.0.0',
        'urllib3==1.24.1',
        'wheel==0.33.1',
        'aws-requests-auth>=0.3.0'
    ]
)
